name: Deploy to App Engine

on:
  push:
    branches:
      - main

env:
  CLOUDSDK_CORE_PROJECT: 'vernal-dispatch-303100'

jobs:
  deploy-app-engine:
    name: Deploy App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: example-app/app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
